# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the
# server process.

# theme settings
theme: #"lone-wolf-theme"
remote_theme: "manid2/lone-wolf-theme"
bootswatch_theme: "united" # cerulean, spacelab, united

# site settings, follows the order used in jekyll-seo-tag plugin
lang: "en_US"
title: "Lone Wolf Theme"
description: "A simple bootstrap based jekyll theme."
url: https://manid2.github.io
baseurl: "/lone-wolf-theme"
author: mani_d2
twitter:
  username: mani_d2 # should be site's username
  card: summary
logo: assets/images/lwt-logo-wolf-v2.png # PNG is SEO friendly
# use below when there are social links for site
#social:
#  name: Mani Kumar
#  links:
#    - https://twitter.com/mani_d2
#    - https://www.linkedin.com/in/manid2/
#    - https://github.com/manid2
# site verifications,
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234
  baidu: # 1234

# comments settings
comments:
  provider: false
  disqus:
    shortname:

# feed
atom_feed:
  path: # blank (default) uses feed.xml

# site search settings
search: # true, false (default)
search_full_content: # true, false (default)
search_provider: # google

google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true

# Analytics
analytics:
  provider: "google-gtag" # false (default), "google-gtag", "custom"
  google:
    tracking_id: "UA-138748532-1"
    anonymize_ip: # true, false (default)

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore /docs in theme
  - /test # ignore /test in theme
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
# http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: "/blog/page/:num/"
timezone: "" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# site defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      show_hero: true
      show_author: true
      show_toc: true
      share: true
      show_comments: false
      show_ads: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      show_ads: true
  # any page
  - scope:
      path: ""
    values:
      # for SEO and social sharing
      image: assets/images/lwt-logo-wolf-v2.png
      image_alt: Lone Wolf Theme logo version 2
